import type { Rng } from './rng'
import { randInt } from './rng'

// A league runs ~1,700+ players at once across 32 teams, and a stat-leader
// board is scanning the same handful of names every week - a pool this
// small (previously 20x20 = 400 combinations) guaranteed constant first-name
// collisions among the players anyone actually looks at. Widened well past
// what the birthday-paradox math needs to make that rare in practice.
const FIRST_NAMES = [
  'James', 'Michael', 'David', 'Chris', 'Marcus', 'Jordan', 'Tyler', 'Brandon',
  'Justin', 'Andre', 'DeShawn', 'Malik', 'Ethan', 'Cole', 'Dante', 'Trevor',
  'Xavier', 'Isaiah', 'Cameron', 'Jalen', 'Aaron', 'Adrian', 'Alex', 'Anthony',
  'Antonio', 'Austin', 'Blake', 'Bobby', 'Braxton', 'Brady', 'Brayden', 'Brendan',
  'Brett', 'Bryce', 'Caleb', 'Carlos', 'Carter', 'Chase', 'Christian', 'Clayton',
  'Colin', 'Connor', 'Corey', 'Curtis', 'Damian', 'Damon', 'Daniel', 'Darius',
  'Darnell', 'Deandre', 'Dennis', 'Derek', 'Devin', 'Dominic', 'Donovan', 'Dorian',
  'Dwayne', 'Dylan', 'Eddie', 'Edward', 'Elijah', 'Emmanuel', 'Eric', 'Evan',
  'Ezekiel', 'Frank', 'Gabriel', 'Garrett', 'Gavin', 'George', 'Grant', 'Grayson',
  'Greg', 'Hakeem', 'Harrison', 'Henry', 'Hunter', 'Ian', 'Isaac', 'Ivan',
  'Jace', 'Jack', 'Jackson', 'Jacob', 'Jamal', 'Jamar', 'Jared', 'Jarvis',
  'Jason', 'Javon', 'Jayden', 'Jeff', 'Jeremiah', 'Jeremy', 'Jerome', 'Jesse',
  'Joel', 'John', 'Jonathan', 'Jose', 'Joseph', 'Josh', 'Julian',
  'Kaden', 'Kareem', 'Keith', 'Kelvin', 'Kenneth', 'Kevin', 'Khalil', 'Kobe',
  'Kris', 'Kurt', 'Kyle', 'Lamar', 'Landon', 'Lance', 'Larry', 'Leon',
  'Levi', 'Liam', 'Logan', 'Lonnie', 'Louis', 'Lucas', 'Luke', 'Manuel',
  'Marco', 'Mario', 'Mark', 'Martin', 'Mason', 'Mathias', 'Matthew', 'Maurice',
  'Max', 'Melvin', 'Micah', 'Miguel', 'Mitchell', 'Nathan', 'Nathaniel', 'Nick',
  'Noah', 'Nolan', 'Omar', 'Oscar', 'Owen', 'Patrick', 'Paul', 'Pedro',
  'Percy', 'Perry', 'Peter', 'Phillip', 'Preston', 'Quentin', 'Quincy', 'Raheem',
  'Ramon', 'Randall', 'Raul', 'Ray', 'Reggie', 'Reid', 'Rex', 'Ricardo',
  'Richard', 'Ricky', 'Robert', 'Rodney', 'Roman', 'Ronald', 'Ross', 'Roy',
  'Ryan', 'Sam', 'Sean', 'Sergio', 'Seth', 'Shane', 'Shawn', 'Simon',
  'Spencer', 'Stephen', 'Steven', 'Terrence', 'Terry', 'Theo', 'Thomas', 'Tim',
  'Todd', 'Tony', 'Travis', 'Tremaine', 'Trent', 'Tristan', 'Troy', 'Tyrell',
  'Tyrese', 'Tyson', 'Victor', 'Vincent', 'Wade', 'Walter', 'Warren', 'Wesley',
  'Will', 'William', 'Wyatt', 'Zach', 'Zane',
]

const LAST_NAMES = [
  'Johnson', 'Williams', 'Brown', 'Davis', 'Miller', 'Wilson', 'Moore',
  'Taylor', 'Anderson', 'Thomas', 'Jackson', 'White', 'Harris', 'Martin',
  'Thompson', 'Robinson', 'Walker', 'Young', 'Allen', 'King', 'Adams',
  'Alexander', 'Armstrong', 'Arnold', 'Austin', 'Bailey', 'Baker', 'Barnes',
  'Bell', 'Bennett', 'Bishop', 'Black', 'Blair', 'Booker', 'Boone', 'Bowman',
  'Boyd', 'Bradley', 'Brady', 'Brewer', 'Bridges', 'Briggs', 'Brooks', 'Bryant',
  'Burke', 'Burns', 'Burton', 'Butler', 'Byrd', 'Cain', 'Cameron', 'Campbell',
  'Cannon', 'Carey', 'Carlson', 'Carpenter', 'Carr', 'Carroll', 'Carter', 'Castro',
  'Chambers', 'Chandler', 'Chapman', 'Chavez', 'Clark', 'Clay', 'Coleman', 'Collier',
  'Collins', 'Cook', 'Cooper', 'Cross', 'Cruz', 'Cunningham', 'Curtis', 'Dawson',
  'Day', 'Dean', 'Delgado', 'Dennis', 'Diaz', 'Dixon', 'Dodson', 'Dorsey',
  'Douglas', 'Doyle', 'Duncan', 'Dunn', 'Dyer', 'Edwards', 'Elliott', 'Ellis',
  'English', 'Evans', 'Farmer', 'Ferguson', 'Fields', 'Fisher', 'Fitzgerald', 'Fletcher',
  'Flores', 'Floyd', 'Ford', 'Foster', 'Fox', 'Franklin', 'Frazier', 'Freeman',
  'Fuller', 'Gaines', 'Gardner', 'Garrett', 'Garrison', 'Gibson', 'Gilbert', 'Gill',
  'Glover', 'Gomez', 'Gonzales', 'Goodwin', 'Gordon', 'Graham', 'Grant', 'Graves',
  'Gray', 'Green', 'Greer', 'Griffin', 'Gross', 'Guerrero', 'Hale', 'Hall',
  'Hamilton', 'Hammond', 'Hancock', 'Hansen', 'Hardy', 'Harmon', 'Harper', 'Harrell',
  'Harrington', 'Harrison', 'Hart', 'Hawkins', 'Hayes', 'Henderson', 'Henry', 'Hernandez',
  'Herrera', 'Hicks', 'Higgins', 'Hill', 'Hines', 'Hobbs', 'Hoffman', 'Holland',
  'Holloway', 'Holmes', 'Holt', 'Hopkins', 'Horn', 'Houston', 'Howard', 'Howell',
  'Hudson', 'Hughes', 'Hunt', 'Hunter', 'Ingram', 'Jacobs', 'James', 'Jefferson',
  'Jenkins', 'Jennings', 'Jimenez', 'Jones', 'Jordan', 'Joyce', 'Keller', 'Kelley',
  'Kelly', 'Kennedy', 'Kent', 'Kerr', 'Klein', 'Knapp', 'Knight', 'Knox',
  'Lambert', 'Landry', 'Lane', 'Larson', 'Lawrence', 'Lawson', 'Lee', 'Lewis',
  'Lindsey', 'Little', 'Logan', 'Long', 'Lopez', 'Lott', 'Love', 'Lowe',
  'Lucas', 'Lynch', 'Mack', 'Maddox', 'Malone', 'Mann', 'Manning', 'Marsh',
  'Marshall', 'Mason', 'Massey', 'Mathis', 'Maxwell', 'May', 'Mays', 'Mcdaniel',
  'Mcdonald', 'Mckenzie', 'Medina', 'Melton', 'Mercer', 'Meyer', 'Mills', 'Mitchell',
  'Montgomery', 'Morales', 'Morgan', 'Morris', 'Morrison', 'Morrow', 'Murphy', 'Murray',
  'Myers', 'Nash', 'Nelson', 'Newman', 'Newton', 'Nguyen', 'Nichols', 'Nixon',
  'Norman', 'Norris', 'Nunez', 'Oconnor', 'Oliver', 'Orozco', 'Ortiz', 'Osborne',
  'Owens', 'Pace', 'Padilla', 'Palmer', 'Parker', 'Parks', 'Parrish', 'Patterson',
  'Payne', 'Pearson', 'Peck', 'Perez', 'Perkins', 'Perry', 'Peters', 'Petersen',
  'Peterson', 'Phelps', 'Phillips', 'Pierce', 'Pittman', 'Pollard', 'Poole', 'Pope',
  'Porter', 'Powell', 'Powers', 'Pratt', 'Preston', 'Price', 'Prince', 'Pugh',
  'Quinn', 'Ramirez', 'Ramos', 'Randall', 'Ray', 'Reed', 'Reese', 'Reeves',
  'Reid', 'Reyes', 'Reynolds', 'Rhodes', 'Rice', 'Rich', 'Richards', 'Richardson',
  'Riley', 'Rivas', 'Rivera', 'Roach', 'Roberson', 'Roberts', 'Robertson', 'Rodgers',
  'Rodriguez', 'Rogers', 'Rollins', 'Romero', 'Rosales', 'Rose', 'Ross', 'Rowe',
  'Roy', 'Russell', 'Salazar', 'Sanchez', 'Sanders', 'Santos', 'Savage', 'Schmidt',
  'Schultz', 'Schwartz', 'Scott', 'Sellers', 'Sexton', 'Shaffer', 'Shannon', 'Sharp',
  'Shaw', 'Shelton', 'Sherman', 'Shields', 'Short', 'Silva', 'Simmons', 'Simon',
  'Simpson', 'Sims', 'Singleton', 'Skinner', 'Sloan', 'Small', 'Smith', 'Snyder',
  'Solis', 'Solomon', 'Soto', 'Sparks', 'Spencer', 'Stanley', 'Steele', 'Stephens',
  'Stevens', 'Stewart', 'Stokes', 'Stone', 'Strickland', 'Suarez', 'Sullivan', 'Summers',
  'Sutton', 'Sweeney', 'Tanner', 'Tate', 'Tucker', 'Turner', 'Underwood', 'Valdez',
  'Valencia', 'Valentine', 'Valenzuela', 'Vance', 'Vargas', 'Vasquez', 'Vaughn', 'Vega',
  'Velasquez', 'Villanueva', 'Wade', 'Wagner', 'Waller', 'Ward', 'Warner', 'Warren',
  'Washington', 'Waters', 'Watkins', 'Watson', 'Watts', 'Weaver', 'Webb', 'Weber',
  'Webster', 'Welch', 'Wells', 'West', 'Wheeler', 'Whitaker', 'Whitehead', 'Whitfield',
  'Whitney', 'Wiggins', 'Wilkerson', 'Wilkins', 'Wilkinson', 'Williamson', 'Willis', 'Wolf',
  'Wolfe', 'Wong', 'Woodard', 'Woods', 'Wright', 'Wyatt', 'Yates', 'York',
  'Zamora', 'Zimmerman',
]

export function randomName(rng: Rng) {
  return {
    firstName: FIRST_NAMES[randInt(rng, 0, FIRST_NAMES.length - 1)],
    lastName: LAST_NAMES[randInt(rng, 0, LAST_NAMES.length - 1)],
  }
}
